const spotifyEins = require('../songdata0.json')
const spotifyZwei = require('../songdata1.json')
const spotifyDrei = require('../songdata2.json')
const spotifyVier = require('../songdata3.json')
const spotify = spotifyEins.concat(spotifyZwei, spotifyDrei, spotifyVier)

console.log(spotifyEins.length)
console.log(spotifyZwei.length)
console.log(spotifyDrei.length)
console.log(spotifyVier.length)
console.log(spotify.length)